import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

def apps():
    st.title("Market Reconsideration")
    st.write('1. Free shipping memiliki daya tarik khusus atau spesial dalam menarik perhatian pembeli baru dalam marketing strategy free shipping adalah strategi yang mengimplementasikan "zero price effect" dan berdasarkan Deloitte holiday retail survey 2020 customer lebih memprioritaskan untuk berbelanja dengan layanan free shipping (85%) dibandingkan fast shipping (15%) calon pembeli biasanya juga rentan untuk melakukan cancel purchase apabila terdapat additional cost saat checkout seperti biaya admin, biaya platform, dsb. oleh karena itu free shipping berdampak untuk memberikan dorongan kepada calon customer untuk segera checkout pesanannya dan saat ini melihat kebiasaan berbelanja di Indonesia free shipping menjadi salah satu kebutuhan utama pembeli saat melakukan checkout pesanan\n')
    st.write('2. Flash sale biasanya digunakan sebagai alat promosi produk secara musiman atau sebagai periode bagi penjual untuk menghabiskan stok produk lama namun strategy flash sale juga mempunyai peran penting yaitu untuk meningkatkan frekuensi penjualan, mempertahankan traffic customer atau follower toko, dan juga membuat brand produk lebih dikenal oleh calon calon pembeli baru\n')
    st.write('3. Product Bundling biasanya digunakan untuk mengurangi jumlah produk sisa, atau biasanya produk yang kurang laris dibundling dengan produk best selling dengan harga yang lebih murah dibandingkan membeli satuan, strategy bundling membuat produk yang kurang laris trafficnya terdongkrak oleh produk best seller. Dalam bidang Fashion biasanya ada produk yang memang didesain atau dibuat dalam satu paket agar customer tidak bingung dalam menentukan mode pakaian. Keuntungan product bundling antara lain meningkatkan average checkout basket, meningkatkan volume penjualan, menghemat biaya packing dan meningkatkan pengalaman berbelanja customer\n')
    st.write('4. Wholesale adalah strategy penjualan yang biasanya diterapkan oleh perusahaan B2B dimana barang yang dijual dalam kuantitas banyak dengan rate harga yang lebih rendah dibandingkan menjual satuan namun dalam industri Fashion strategy ini kurang disarankan apabila penjual menerapkan strategy penjualan DTC(Direct to Consumer) karena wholesale ini biasanya marak digunakan untuk menjual barang barang kebutuhan primer maupun sekunder namun untuk barang barang fashion yang bersifat tersier strategy ini dapat mengurangi tingkat eksklusif dari barang yang dijual, untuk pasar Indonesia biasanya perusahaan yang menerapkan strategy ini mempunyai tujuan untuk membentuk jaringan distributor atau menarik para reseller/dropshipper')
